# These are supported funding model platforms
I am extremely grateful for your generous donations and financial support. Your contributions have made a significant impact on my educational journey, 
and I cannot thank you enough. Your kindness and belief in my potential have motivated me to work harder towards achieving my goals. I am truly blessed to have your support, 
and I will make sure to utilize these resources wisely to pursue my dreams. Thank you from the bottom of my heart for investing in my future.

patreon: https://www.patreon.com/TomasAlguilar
custom: https://www.buymeacoffee.com/tomaselcapD
